### PR TITLE
feat: enable lazy-loading by event and autoload func

### PR DESCRIPTION
**Pull request by younger-1**
May this PR violates the conciseness in itself compared to `vim-plug`, but I think it may be useful to people who'd like more lazy-load options to control their plugins.

### CODE REVIEW

**Comment by tani** [comment]
Thank you for the nice improvement.
Could I offer adding tests and document for the stability and mentenancability?

Best

**Comment by younger-1** [comment]
Surely, the PR is incomplete so do whatever as you wish

**Comment by tani** [comment]
I am busy now. The new feature might be a low priority. Please wait until I complete your pull request.

**Comment by tani** [comment]
Thank you for your contribution! I have added them ❤️

**Comment by younger-1** [comment]
TYVM!

**Pull request closed without merging**
