### PR TITLE
add init function for setting configuration variable

### PR DESCRIPTION
**Pull request by ryoppippi**
Packer style init function
https://github.com/wbthomason/packer.nvim/blob/master/doc/packer.txt

### CODE REVIEW

**Comment by tani** [comment]
Thank you for the great contribution. Would you mind to add the documentation for users?

**Comment by ryoppippi** [comment]
OK. 	
Shoule I need to write documentation about other lua functions?

**Comment by tani** [comment]
Ah, that's a fantastic proposal. Thank you so much!

**Comment by ryoppippi** [comment]
OK, I'll create a new PR about lua documentation.

**Comment by tani** [comment]
Great. Thank you again.

**Pull request merged**
